/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlinebanking;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class ForgotPass extends javax.swing.JFrame {

    public static String AccountNo;
    public Connection conn;
    private static String DB_URL ="jdbc:sqlserver://localhost:1500;" 
            + "databaseName=NTD_Bank;" + "integratedSecurity=true";
    private static String USER_NAME = "sa";
    private static String PASSWORD = "03082004khoi";
    /**
     * Creates new form ForgotPass
     */
    public ForgotPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        AccountNum = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JTextField();
        UsernameLB = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        VerifyIdentityBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153), 4));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/verify-profile.png"))); // NOI18N

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/goback.png"))); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        Heading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 204, 153));
        Heading.setText("First Check It's You");

        AccountNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AccountNum.setText("Enter Account Number");

        AccountNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AccountNumber.setToolTipText("");

        UsernameLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsernameLB.setText("Enter Username");

        Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        VerifyIdentityBtn.setBackground(new java.awt.Color(0, 204, 153));
        VerifyIdentityBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VerifyIdentityBtn.setForeground(new java.awt.Color(255, 255, 255));
        VerifyIdentityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/check-sm.png"))); // NOI18N
        VerifyIdentityBtn.setText("Verify Identity");
        VerifyIdentityBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerifyIdentityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerifyIdentityBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addContainerGap(703, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Logo)
                        .addGap(351, 351, 351))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Heading)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountNum)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UsernameLB)
                                .addComponent(Username)
                                .addComponent(AccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))))
                .addGap(219, 219, 219))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(VerifyIdentityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(Heading)
                .addGap(26, 26, 26)
                .addComponent(AccountNum)
                .addGap(18, 18, 18)
                .addComponent(AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsernameLB)
                .addGap(18, 18, 18)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(VerifyIdentityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void VerifyIdentityBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyIdentityBtnMouseClicked
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(DB_URL,USER_NAME,PASSWORD);
            String query = "Select * from LoginDetail where AccountNumber=? and Username=?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,AccountNumber.getText());
            pst.setString(2,Username.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                AccountNo = AccountNumber.getText();
                setVisible(false);
                dispose();
                new ChangePassword().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Net Banking Cannot Find Your Information. Call to bank if you need help!");
                AccountNumber.setText("");
                Username.setText("");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_VerifyIdentityBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNum;
    private javax.swing.JTextField AccountNumber;
    private javax.swing.JLabel BackBtn;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameLB;
    private javax.swing.JButton VerifyIdentityBtn;
    // End of variables declaration//GEN-END:variables
}
