/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlinebanking;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class InfoCreate extends javax.swing.JFrame {
    public static String AccNumber;
    public Connection conn;
    private static String DB_URL ="jdbc:sqlserver://localhost:1500;" 
            + "databaseName=NTD_Bank;" + "integratedSecurity=true";
    private static String USER_NAME = "sa";
    private static String PASSWORD = "03082004khoi";

    /**
     * Creates new form InfoCreate
     */
    public InfoCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        FirstNameTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        LastNameTF = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        GenderTF = new javax.swing.JTextField();
        AccNum = new javax.swing.JTextField();
        CheckBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/verify-profile.png"))); // NOI18N

        Heading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 204, 153));
        Heading.setText("Verify Your Bank Account");

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FirstName.setText("First Name:");

        LastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LastName.setText("Last Name:");

        Phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Phone.setText("Phone:");

        Gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Gender.setText("Gender:");

        AccountNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AccountNumber.setText("Account Number:");

        Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address.setText("Address:");

        FirstNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        PhoneTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        LastNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AddressTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        GenderTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AccNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        CheckBtn.setBackground(new java.awt.Color(0, 204, 153));
        CheckBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckBtn.setForeground(new java.awt.Color(255, 255, 255));
        CheckBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white-search-person.png"))); // NOI18N
        CheckBtn.setText("Search");
        CheckBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/goback.png"))); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(CheckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(Logo)
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(Heading)
                        .addGap(210, 210, 210))))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FirstName)
                        .addComponent(FirstNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(GenderTF))
                    .addComponent(Gender)
                    .addComponent(AccountNumber)
                    .addComponent(AccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phone)
                    .addComponent(LastName)
                    .addComponent(LastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Logo)
                        .addGap(18, 18, 18)
                        .addComponent(Heading)
                        .addGap(66, 66, 66)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName)
                            .addComponent(LastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender)
                            .addComponent(Phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenderTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(PhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(AccountNumber))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Address)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(CheckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void CheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBtnActionPerformed
        // TODO add your handling code here:
        String PhoneNum = PhoneTF.getText();
        String AccountNo = AccNum.getText();
        boolean Checker = true;
        if(PhoneNum.matches("^[0-9]*$") && PhoneNum.length() <= 11)
        {
            Checker = true;
            PhoneTF.setBackground(new Color(0,204,153));
        }
        else
        {
            Checker = false;
            PhoneTF.setBackground(new Color(246, 53, 40));
        }
        if(AccountNo.matches("^[0-9]*$") && AccountNo.length() <= 12)
        {
            Checker = true;
            AccNum.setBackground(new Color(0,204,153));
        }
        else
        {
            Checker = false;
            AccNum.setBackground(new Color(246, 53, 40));
        }
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(DB_URL,USER_NAME,PASSWORD);
            String query = "Select * from CustomerDetail where FirstName=? and LastName=? and Gender=? and Phone=? and AccountNumber=? and Address=?";
            PreparedStatement pre = conn.prepareStatement(query);
            pre.setString(1,FirstNameTF.getText());
            pre.setString(2, LastNameTF.getText());
            pre.setString(3, GenderTF.getText());
            pre.setString(4, PhoneTF.getText());
            pre.setString(5, AccNum.getText());
            pre.setString(6, AddressTF.getText());
            ResultSet rs = pre.executeQuery();
            if(rs.next())
            {
                AccNumber = AccNum.getText();
                try
                {
                    String query2 = "Select * from LoginDetail where AccountNumber=?";
                    PreparedStatement pst = conn.prepareStatement(query2);
                    pst.setString(1, AccNum.getText());
                    ResultSet rs2 = pst.executeQuery();
                    if(rs2.next())
                    {
                        JOptionPane.showMessageDialog(null, "You Have Already Created Account. Please Login or Call to Bank !");
                        setVisible(false);
                        new Login().setVisible(true);
                        dispose();
                    }
                    else
                    {
                        setVisible(false);
                        dispose();
                        new CreateAccount().setVisible(true);
                        FirstNameTF.setText("");
                        LastNameTF.setText("");
                        GenderTF.setText("");
                        PhoneTF.setText("");
                        AccNum.setText("");
                        AddressTF.setText("");
                        
                    }
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Credential ! Please Enter Valid Detail Or Call To Bank","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            conn.close();
        }catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "We Cannot Communicate With Server! \n Please Check Your internet Connection or call to bank");
        }
    }//GEN-LAST:event_CheckBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNum;
    private javax.swing.JLabel AccountNumber;
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JLabel BackBtn;
    private javax.swing.JPanel Background;
    private javax.swing.JButton CheckBtn;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField GenderTF;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTF;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField PhoneTF;
    // End of variables declaration//GEN-END:variables
}
