/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlinebanking;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    public static String AccountNum;
    private static String DB_URL ="jdbc:sqlserver://localhost:1500;" 
            + "databaseName=NTD_Bank;" + "integratedSecurity=true";
    private static String USER_NAME = "sa";
    private static String PASSWORD = "03082004khoi";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        subHeading = new javax.swing.JLabel();
        CreateAccPanel = new javax.swing.JPanel();
        CreateAccount = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        ForgotPassPanel = new javax.swing.JPanel();
        ForgotPass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LoginProfile = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        PassLb = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        PasswordTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);

        BasePanel.setBackground(new java.awt.Color(255, 255, 255));

        SideBar.setBackground(new java.awt.Color(0, 204, 153));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/museum-sm.png"))); // NOI18N

        Heading.setBackground(new java.awt.Color(255, 255, 255));
        Heading.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("NTD Bank");

        subHeading.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        subHeading.setForeground(new java.awt.Color(255, 255, 255));
        subHeading.setText("Online Banking");

        CreateAccPanel.setBackground(new java.awt.Color(0, 204, 153));
        CreateAccPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreatePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMouseExited(evt);
            }
        });

        CreateAccount.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white-addAccount.png"))); // NOI18N
        CreateAccount.setText("Create Account");

        javax.swing.GroupLayout CreateAccPanelLayout = new javax.swing.GroupLayout(CreateAccPanel);
        CreateAccPanel.setLayout(CreateAccPanelLayout);
        CreateAccPanelLayout.setHorizontalGroup(
            CreateAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(CreateAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateAccPanelLayout.setVerticalGroup(
            CreateAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ExitPanel.setBackground(new java.awt.Color(0, 204, 153));
        ExitPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMouseExited(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white-logout-logo.png"))); // NOI18N
        Exit.setText("Exit");

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ForgotPassPanel.setBackground(new java.awt.Color(0, 204, 153));
        ForgotPassPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPassPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMouseExited(evt);
            }
        });

        ForgotPass.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        ForgotPass.setForeground(new java.awt.Color(255, 255, 255));
        ForgotPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white-forgetpass.png"))); // NOI18N
        ForgotPass.setText("Forgot Password");

        javax.swing.GroupLayout ForgotPassPanelLayout = new javax.swing.GroupLayout(ForgotPassPanel);
        ForgotPassPanel.setLayout(ForgotPassPanelLayout);
        ForgotPassPanelLayout.setHorizontalGroup(
            ForgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPassPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ForgotPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ForgotPassPanelLayout.setVerticalGroup(
            ForgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotPassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ForgotPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateAccPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Logo))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Heading))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(subHeading)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(ForgotPassPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subHeading)
                .addGap(35, 35, 35)
                .addComponent(CreateAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ForgotPassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LoginProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login-profile.png"))); // NOI18N

        welcome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 204, 153));
        welcome.setText("Welcome");

        UsernameTF.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        UsernameTF.setToolTipText("Enter your Username");

        Username.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        Username.setText("Username");

        PassLb.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        PassLb.setText("Password");

        Login.setBackground(new java.awt.Color(0, 204, 153));
        Login.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/padlock-small.png"))); // NOI18N
        Login.setText("Login");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        PasswordTF.setToolTipText("Enter your Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(welcome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username)
                            .addComponent(UsernameTF)
                            .addComponent(PassLb)
                            .addComponent(PasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(LoginProfile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome)
                .addGap(33, 33, 33)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PassLb)
                .addGap(18, 18, 18)
                .addComponent(PasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMouseEntered
        // TODO add your handling code here:
        if(evt.getSource() == CreateAccPanel)
        {
            CreateAccPanel.setBackground(new Color(0,255,153));
        }
        if(evt.getSource() == ExitPanel)
        {
            ExitPanel.setBackground(new Color(0,255,153));
        }
        if(evt.getSource() == ForgotPassPanel)
        {
            ForgotPassPanel.setBackground(new Color(0,255,153));
        }
    }//GEN-LAST:event_PanelMouseEntered

    private void PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMouseExited
        // TODO add your handling code here:
        if(evt.getSource() == CreateAccPanel)
        {
            CreateAccPanel.setBackground(new Color(0,204,153));
        }
        if(evt.getSource() == ExitPanel)
        {
            ExitPanel.setBackground(new Color(0,204,153));
        }
        if(evt.getSource() == ForgotPassPanel)
        {
            ForgotPassPanel.setBackground(new Color(0,204,153));
        }
    }//GEN-LAST:event_PanelMouseExited

    private void CreatePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatePanelMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new InfoCreate().setVisible(true);
    }//GEN-LAST:event_CreatePanelMouseClicked

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connect = DriverManager.getConnection(DB_URL,USER_NAME,PASSWORD);
            String query = "Select * from LoginDetail where Username=? and Password=?";
            PreparedStatement pre = connect.prepareStatement(query);
            pre.setString(1,UsernameTF.getText());
            pre.setString(2,PasswordTF.getText());
            ResultSet rs = pre.executeQuery();
            if(rs.next())
            {
                AccountNum = rs.getString("AccountNumber");
                setVisible(false);
                dispose();
                new MainMenu().setVisible(true);
                
            }
            else if("".equals(UsernameTF.getText()) && "".equals(PasswordTF.getText())){
                JOptionPane.showMessageDialog(null, "Please enter Username and Password !","Information",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Credential !","Warning",JOptionPane.ERROR_MESSAGE);
                UsernameTF.setText("");
                PasswordTF.setText("");
            }
            connect.close();
        }catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Cannot Connect With Server \n Please Check Your Internet Connection or Call to Bank");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void ForgotPassPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassPanelMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new ForgotPass().setVisible(true);
    }//GEN-LAST:event_ForgotPassPanelMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel CreateAccPanel;
    private javax.swing.JLabel CreateAccount;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JLabel ForgotPass;
    private javax.swing.JPanel ForgotPassPanel;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Login;
    private javax.swing.JLabel LoginProfile;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel PassLb;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subHeading;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
