/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlinebanking;
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Profile extends javax.swing.JFrame {

    public Connection conn;
    public String AccNum = new Login().AccountNum;
    private static String DB_URL ="jdbc:sqlserver://localhost:1500;" 
            + "databaseName=NTD_Bank;" + "integratedSecurity=true";
    private static String USER_NAME = "sa";
    private static String PASSWORD = "03082004khoi";
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        ProfileSectionOpen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Heading = new javax.swing.JPanel();
        HeadingProfile = new javax.swing.JLabel();
        ProfileName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AccountNumber = new javax.swing.JLabel();
        ProfileAN = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        ProfileEmail = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        ProfileAddress = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        ProfilePhone = new javax.swing.JLabel();
        AccounType = new javax.swing.JLabel();
        TypeCard = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        ProfileUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Heading.setBackground(new java.awt.Color(0, 204, 153));

        HeadingProfile.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        HeadingProfile.setForeground(new java.awt.Color(255, 255, 255));
        HeadingProfile.setText("PROFILE");

        javax.swing.GroupLayout HeadingLayout = new javax.swing.GroupLayout(Heading);
        Heading.setLayout(HeadingLayout);
        HeadingLayout.setHorizontalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeadingProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        HeadingLayout.setVerticalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadingLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HeadingProfile)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ProfileName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfileName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/male-profile.png"))); // NOI18N
        ProfileName.setText("Your Name Here");
        ProfileName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        AccountNumber.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        AccountNumber.setText("Account Number:");

        ProfileAN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfileAN.setText("jLabel1");

        Email.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Email.setText("Email:");

        ProfileEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfileEmail.setText("jLabel5");

        Address.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Address.setText("Address:");

        ProfileAddress.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfileAddress.setText("jLabel5");

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/goback.png"))); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        Phone.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Phone.setText("Phone:");

        ProfilePhone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfilePhone.setText("jLabel5");

        AccounType.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        AccounType.setText("Account Type:");

        TypeCard.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TypeCard.setText("jLabel5");

        Username.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Username.setText("Username:");

        ProfileUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ProfileUsername.setText("jLabel1");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 183, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addComponent(ProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Phone)
                                    .addComponent(AccounType)
                                    .addComponent(Address)
                                    .addComponent(Email))
                                .addGap(88, 88, 88)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProfileEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                    .addComponent(ProfileAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProfilePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TypeCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username)
                                    .addComponent(AccountNumber))
                                .addGap(58, 58, 58)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProfileUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                    .addComponent(ProfileAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BackBtn))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ProfileName)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNumber)
                    .addComponent(ProfileAN))
                .addGap(45, 45, 45)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username))
                .addGap(37, 37, 37)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(ProfileEmail))
                .addGap(38, 38, 38)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(ProfileAddress))
                .addGap(52, 52, 52)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfilePhone)
                    .addComponent(Phone))
                .addGap(53, 53, 53)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeCard)
                    .addComponent(AccounType))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    public void ProfileSectionOpen()
    {
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(DB_URL,USER_NAME,PASSWORD);
            String query = "Select LoginDetail.*,CustomerDetail.* from LoginDetail inner join CustomerDetail on LoginDetail.AccountNumber = CustomerDetail.AccountNumber where LoginDetail.AccountNumber = '"+AccNum+"' ";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                ProfileName.setText(rs.getString("LastName")+" "+rs.getString("FirstName"));
                ProfileAN.setText(rs.getString("AccountNumber"));
                ProfileUsername.setText(rs.getString("Username"));
                ProfileEmail.setText(rs.getString("Email"));
                ProfilePhone.setText(rs.getString("Phone"));
                ProfileAddress.setText(rs.getString("Address"));
                TypeCard.setText(rs.getString("AccountType"));
                String Gender = rs.getString("Gender");
                if("Female".equals(Gender))
                {
                    ProfileName.setIcon(new ImageIcon("D:\\Study\\UEF\\Java Technology\\B01E_Group4_FinalProject\\OnlineBanking\\src\\assets\\women-profile.png"));
                }
            }
            conn.close();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccounType;
    private javax.swing.JLabel AccountNumber;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel BackBtn;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Heading;
    private javax.swing.JLabel HeadingProfile;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel ProfileAN;
    private javax.swing.JLabel ProfileAddress;
    private javax.swing.JLabel ProfileEmail;
    private javax.swing.JLabel ProfileName;
    private javax.swing.JLabel ProfilePhone;
    private javax.swing.JLabel ProfileUsername;
    private javax.swing.JLabel TypeCard;
    private javax.swing.JLabel Username;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
